# Sample config for Prometheus.
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
    - /etc/prometheus/rules.yml

{% if grains.get('monitored_hosts') %}
scrape_configs:
  - job_name: hanadb
    static_configs:
      - targets:
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:8001" # 8001: hanadb exporter port
        {% endfor %}

  - job_name: node
    static_configs:
      - targets:
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:9100" # 9100: node exporter port
        {% endfor %}

  - job_name: cluster
    metrics_path: /metrics
    static_configs:
      - targets:
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:9002" # 9002: ha_cluster_exporter metrics
        {% endfor %}
{% endif %}
